In [1]:
!pip3 install pandas

    100% |████████████████████████████████| 10.4MB 60kB/s eta 0:00:01    56% |██████████████████              | 5.9MB 1.2MB/s eta 0:00:04


In [2]:
!pip install sklearn

    100% |████████████████████████████████| 5.5MB 103kB/s ta 0:00:01
    100% |████████████████████████████████| 17.0MB 36kB/s eta 0:00:01
    100% |████████████████████████████████| 24.8MB 24kB/s eta 0:00:011


In [3]:
!pip install numpy

In [22]:
import pandas as pd

In [37]:
data = pd.read_csv('housing.csv')
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [38]:
data = data.iloc[:, :-1]

In [39]:
X = data.iloc[:, 2:-1].values
y = data.iloc[:, -1].values
X

array([[4.1000e+01, 8.8000e+02, 1.2900e+02, 3.2200e+02, 1.2600e+02,
        8.3252e+00],
       [2.1000e+01, 7.0990e+03, 1.1060e+03, 2.4010e+03, 1.1380e+03,
        8.3014e+00],
       [5.2000e+01, 1.4670e+03, 1.9000e+02, 4.9600e+02, 1.7700e+02,
        7.2574e+00],
       ...,
       [1.7000e+01, 2.2540e+03, 4.8500e+02, 1.0070e+03, 4.3300e+02,
        1.7000e+00],
       [1.8000e+01, 1.8600e+03, 4.0900e+02, 7.4100e+02, 3.4900e+02,
        1.8672e+00],
       [1.6000e+01, 2.7850e+03, 6.1600e+02, 1.3870e+03, 5.3000e+02,
        2.3886e+00]])

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [41]:
y

array([452600., 358500., 352100., ...,  92300.,  84700.,  89400.])

In [42]:
import numpy as np
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:, :])

In [43]:
X[:,:] = imputer.transform(X[:,:])

In [44]:
X

array([[4.1000e+01, 8.8000e+02, 1.2900e+02, 3.2200e+02, 1.2600e+02,
        8.3252e+00],
       [2.1000e+01, 7.0990e+03, 1.1060e+03, 2.4010e+03, 1.1380e+03,
        8.3014e+00],
       [5.2000e+01, 1.4670e+03, 1.9000e+02, 4.9600e+02, 1.7700e+02,
        7.2574e+00],
       ...,
       [1.7000e+01, 2.2540e+03, 4.8500e+02, 1.0070e+03, 4.3300e+02,
        1.7000e+00],
       [1.8000e+01, 1.8600e+03, 4.0900e+02, 7.4100e+02, 3.4900e+02,
        1.8672e+00],
       [1.6000e+01, 2.7850e+03, 6.1600e+02, 1.3870e+03, 5.3000e+02,
        2.3886e+00]])

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [46]:
type(X_train)

numpy.ndarray

In [80]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(max_depth=3)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=3, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [63]:
y_pred = regressor.predict(X_test)
y_pred

array([164060.        , 217500.        , 246066.66666667, ...,
       500001.        , 125000.        , 154500.        ])

In [64]:
from sklearn.metrics import mean_squared_error,r2_score

In [65]:
r2_score(y_test, y_pred)

0.39633665893809844

In [66]:
mean_squared_error(y_test, y_pred)

8057656031.281655

In [81]:
from sklearn.tree import export_graphviz 
export_graphviz(regressor, out_file ='tree.dot', 
			feature_names =['housing_median_age','total_rooms','total_bedrooms','population','households','median_income']) 
